apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: atogemini-com-tls
spec:
    secretName: atogemini-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: atogemini.com
    dnsNames:
        - atogemini.com
        - www.atogemini.com